# Generated by Django 6.0.3 on 2026-03-20 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('USER_ADMIN', 'Admin'), ('USER_INTERN', 'Intern')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=255)),
                ('task_status', models.CharField(choices=[('TASK_STATUS_PENDING', 'Pending'), ('TASK_STATUS_ASSIGNED', 'Assigned'), ('TASK_STATUS_COMPLETED', 'Completed')], default='TASK_STATUS_PENDING', max_length=255)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assigned_by', to='portal.portaluser')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assigned_to', to='portal.portaluser')),
            ],
        ),
    ]
